export default [
    'I know the best spot in town for ',
    'I get along best with people ',
    'My role in the friend group ',
    'I want someone who ',
    'I’m convinced that ',
    "Don't hate me if ",
    'A life goal of mine ',
    'I geek out on ',
    'I flip out over ',
    'I’m weirdly attracted to ',
    'A social cause I care about ',
    'Favorite holiday tradition ',
    'I’m overly competitive about ',
    'I’m actually legitimately bad at ',
    'Worst fad I participated in ',
    'The award I should be nominated for ',
    'Next vacation spot ',
    'I spend most of my money on ',
    'My most irrational fear ',
    'One thing I’ll never do again ',
    'Weirdest gift I have given or received ',
    'My ideal fake sick day ',
    'My happy place ',
    "I'll know it's time to delete this app when ",
    'This year I really want to ', 
    'Dating me is like ', 
    'A shower thought I recently had ',
    'This year I really want to ', 
    "We're the same type of weird if ', 
    "If you saw the targeted ads I get, you'd think I'm ",
    'My zodiac sign is ',
    'Most of all I want to meet someone who deserves my ', 
    "If you ever need to bail me out of jail, it'll be because ",
    "Do you think advanced primates like chimps and apes should be afforded some degree of human rights? ",
    'I need some me time to ', 
    'I prefer to sleep ', 
    "What is your backup plan if you can't find a date on a friday night ", 
    'My kink is ', 
];
